### ISSUE TITLE
OutOfMemoryError in thread "firebase-default-14"

### ISSUE THREAD

**Issue by pietro3092** [firebase/firebase-admin-java#191] opened 2018-07-10 14:25 UTC
Hi,

I am using firebase-admin-java library to access firebase from my spring application on Tomcat 9. I am getting Out Of Memory error: 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "firebase-default-14"
Sometimes it is "firebase-default-14", sometimes even "firebase-default-96". 

I found similar problem on stackoverflow:
https://stackoverflow.com/questions/20818428/how-to-terminate-firebase-thread-in-spring-mvc-app

**Comment by hiranya911** [comment] 2018-07-10 18:12
Unless you can provide a reproducible test case, there's nothing much we can do about it. It is also unlikely to be an issue with the SDK, since the SDK keeps minimum state, and if there was a memory leak more developers would be affected by it. 

The thread IDs in OOM errors don't usually have anything to do with the root cause. As you may know when the JVM is at the brink of running OOM, any of the active threads may throw an OutOfMemoryError. The SDK does most of its work on the `firebase-default` thread pool, so it's no surprise that one of those threads end up throwing the exception.

The more likely causes are:
1. your application genuinely doesn't have enough memory to handle its workload
2. a possible memory leak in the application code

You should probably take some heap and thread dumps and see what's going on. Since you seem to be having thread IDs with numbers as high as 96, I'd start with a `jstack` log, and see how many threads are active when the process is at OOM. The SDK uses a cached thread pool by default with no upper bound, so that is one place where a lot of memory could be spent. But that is usually in correlation to your own workload.

**Comment by hiranya911** [comment] 2018-08-03 20:37
Closing this as there's not enough details to debug the issue.

**Closed by hiranya911** 2018-08-03 20:37 UTC
