### ISSUE TITLE
Firebase admin / Appengine timeouts

### ISSUE THREAD

**Issue by samodadela** [firebase/firebase-admin-java#111] opened 2017-12-09 21:37 UTC
Hi, 

We are using Firebase Admin to send messages from AppEngine. All works fine most of the time... however every now and then all Firebase calls start timing out (we wait for 20 seconds max). The calls are being made on a B2 class (configured for max 2 instances) which is fed data via task queue. During normal operation each call takes about 100-150ms. If we kill the instance everything starts working OK until next time. This was tested on 5.5.0 and also 5.4.0. Most of the calls are updateChildrenAsync(). What's also weird is that timeouts happen only on one of the two database shards (we are sharding databases within a single project) we use.

We can reproduce the problem by submitting 1000 jobs (in the end one job calls one updateChildrenAsync() (each job starts an operation and waits for it to complete). So under load it start to timeout. 

Because of that we increased max instances to 5 and changed the class to B4... seems to work fine now. 

I cannot explain to myself why this is happening... Even with limited resources there should be no timeouts ... AppEngine should limit the rate at which the task queue is being processed - it won't flood one instance over its limits. 

So, if someone could explain why this is happening (is Firebase's thread model messing up AppEngine in a negative way?) Is it just that Firebase needs stronger instances? Are there any special considerations when running Firebase on AppEngine? Are there any risks of leaking resources (e.g. threads)?

I apologize because I can't describe the problem in more detail. Any hints on the matter are appreciated.

**Comment by hiranya911** [comment] 2017-12-09 21:47
This is too vague to even attempt  to decipher. Can you please share some more details -- ideally including:
* Java code for FirebaseApp initialization and database access
* appengine-web.xml
* Error logs demonstrating the problem

**Comment by samodadela** [comment] 2017-12-11 08:04
Yeah, sorry for the bad report... Here's the info if it helps.

Initialization... it's a static initializer per instance, each instance can accesses multiple databases within a single project):
               

               try {
                    FirebaseOptions options = new FirebaseOptions.Builder()
                            .setCredentials( GoogleCredentials.fromStream( ResourceLoader.getResourceAsStream( firebaseProjectConfiguration.getServiceAccountPath() ) ) )
                            .setDatabaseUrl( databaseUrl )
                            .build();

                    FirebaseApp.initializeApp( options, projectDatabase );

                } catch( IOException e ) {
                    log.error( "Could not bootstrap Firebase!", e );
                    throw new UnexpectedException( "Could not bootstrap Firebase!" );
                }

appengine_web.xml:

    <runtime>${appengine.runtime}</runtime>
    <url-stream-handler>${appengine.urlStreamHandler}</url-stream-handler>

    <instance-class>${firebase.instance-class}</instance-class>
    <basic-scaling>
        <max-instances>${firebase.max-instances}</max-instances>
        <idle-timeout>10m</idle-timeout>
    </basic-scaling>

example code:

        DatabaseReference mDatabase = getDatabaseReference( firebaseProjectId );
        String key = mDatabase.child( path ).push().getKey();

        LinkedHashMap<String, Object> childUpdates = new LinkedHashMap<>();

        entry.put( jsTag_firebaseEntriesBase_timestamp, ServerValue.TIMESTAMP );
        childUpdates.put( path + "/" + key, entry );

        ApiFuture<Void> request = mDatabase.updateChildrenAsync( childUpdates );
        try {
            request.get( FirebaseConfigurationsHelper.FIREBASE_ADD_ENTRY_TIMEOUT_DEFAULT_SECONDS, TimeUnit.SECONDS );
            Metrics.log( FIREBASE_UPDATE_CHILDREN_ASYNC_OK );
        } catch( InterruptedException e ) {
            log.error( "updateChildrenAsync interrupted!", e );
            Metrics.log( FIREBASE_UPDATE_CHILDREN_ASYNC_INTERRUPTED );
        } catch( ExecutionException e ) {
            log.error( "updateChildrenAsync error!", e );
            Metrics.log( FIREBASE_UPDATE_CHILDREN_ASYNC_ERROR );
        } catch( TimeoutException e ) {
            log.error( "updateChildrenAsync timed out!", e );
            Metrics.log( FIREBASE_UPDATE_CHILDREN_ASYNC_TIMEOUT );
        }


BTW: I had code that was starting an operation (like updateChildrenAsync) and was not waiting for it to complete. Could this mess up the instance or do threads cleanup automatically when exiting the handler?

**Comment by hiranya911** [comment] 2017-12-11 19:36
@samodadela thanks for providing the additional info.

I don't see anything obviously wrong with the code (although I cannot rule it out either, since I can only see a small portion of your app). However, one issue you might be running into is the background thread limit (10) enforced by App Engine. Each database client spawns 4-5 threads, so 2 database instances bring you awfully close to that limit. The behavior once you hit that limit is anybody's guess.

I would recommend you to try this on App Engine's [java8 runtime](https://cloud.google.com/appengine/docs/standard/java/runtime-java8). Use a custom [`ThreadManager`](https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/ThreadManager) when initializing `FirebaseApp`, and specifically avoid using App Engine's background thread factory. See if this yields better results.

You can also enable debug logging in your existing deployments, and see if anything interesting shows up in the logs.

**Comment by samodadela** [comment] 2017-12-11 21:20
@hiranya911 actually production will use 4 shards - i.e. 4 databases... guess I'm over limit already ;(
We do use java8 so I guess I can look into the ThreadManager... do you have an example using ThreadManager? We go live in the next few days so I will see first hand what happens after reaching the limit ;)

**Comment by hiranya911** [comment] 2017-12-11 21:32
@samodadela try the following as a starting point:

```
static class BasicScalingThreadManager extends ThreadManager {

    @Override
    protected ExecutorService getExecutor(@NonNull FirebaseApp firebaseApp) {
      // Use a single-threaded executor which keeps threads alive for 1 minute.
      return new ThreadPoolExecutor(0, 1,
          60L, TimeUnit.SECONDS, new SynchronousQueue<Runnable>(), getThreadFactory());
    }

    @Override
    protected void releaseExecutor(@NonNull FirebaseApp firebaseApp,
        @NonNull ExecutorService executorService) {
      executorService.shutdownNow();
    }

    @Override
    protected ThreadFactory getThreadFactory() {
      // This thread factory will be used by all database-related code.
      return Executors.defaultThreadFactory();
    }
}
```

**Comment by samodadela** [comment] 2017-12-11 21:36
@hiranya911 you said: 

> Each database client spawns 4-5 threads, so 2 database instances bring you awfully close to that limit.

What do you mean by database client? Is it 4-5 per database OR per firebase operation? 

The docs say that for java8 the limit is 50 threads... does that mean I'm good for 50/5 = 10 databases?

**Comment by hiranya911** [comment] 2017-12-11 21:46
4-5 threads per database (i.e. instance of `FirebaseDatabase`). 

The 50 limit is for the "request threads". I'm not sure if the long-running threads spawned by the Admin SDK count against that quota. Without the custom `ThreadManager` they count against the background thread quota, which is only 10.

**Comment by samodadela** [comment] 2017-12-11 21:50
OK, thanks. One more question, please. Should I use the same instance of ThreadManager for all initializeApp() calls or does each one get it's own?

**Comment by hiranya911** [comment] 2017-12-11 21:54
You should be able to use the same instance across multiple apps. 

But I'm surprised that you're using multiple apps. Can you please elaborate a bit on that. Why is it necessary to use multiple app instances?

**Comment by samodadela** [comment] 2017-12-11 22:03
You mean multiple databases? We are sharding on multiple Firebase databases withing a single Firebase project - according to DAU calculations a single database will not be able to handle all the load. 

We did consider (by suggestion from google) Firestore where the limits are much higher. It even promises that sharding is not required... however in it's current status (beta) the limits are still there and we did not get a quote on when the beta will end.

We use Firebase for our chat functionality. The rooms are distributed across databases - we don't have a need for users of one room to interact with users of another (on another db).

**Comment by hiranya911** [comment] 2017-12-11 22:12
My question is more about why do you need to call `FirebaseApp.initializeApp()` multiple times. You should be able to access multiple database instances from the same app, by calling `FirebaseDatabase.getInstance(String url)`.

I would rather call `initializeApp()` once globally (possibly via a `ServletContextListener`), and then use that single global instance for all database calls. If you were starting/stopping multiple apps dynamically, that could also explain some of the weirdness you've seen.

**Comment by samodadela** [comment] 2017-12-11 22:16
You're right... it was because initially we were sharding projects - so the code was handling different projects and we totally forgot about it. 

Thank you very much. You've just cut down my thread count ;)

**Comment by hiranya911** [comment] 2017-12-11 22:26
Note that it will still spawn 4-5 threads per `FirebaseDatabase` instance. But each `FirebaseApp` instance also starts at least one background thread (for proactive OAuth2 token refresh). So based on this, I think you were definitely bumping into the GAE thread limit earlier, and that was probably the most likely cause of the issue.

If we are right, custom `ThreadManager` combined with a single shared `FirebaseApp` instance should help alleviate the problem.

**Comment by samodadela** [comment] 2017-12-11 22:34
I just tried the custom ThreadManager and it doesn't work... not even one request went through. Hmm... 

Can you tell me how to enable logging in Firebase Admin so that I can see what's going on? The gae instance started up (cold start after upload) and all request timed out. 

What I did: 


    private static BasicScalingThreadManager basicScalingThreadManager = new BasicScalingThreadManager();

  ...

                      FirebaseOptions options = new FirebaseOptions.Builder()
                            .setCredentials( GoogleCredentials.fromStream( ResourceLoader.getResourceAsStream( firebaseProjectConfiguration.getServiceAccountPath() ) ) )
                            .setDatabaseUrl( databaseUrl )
                            .setThreadManager( basicScalingThreadManager )
                            .build();

                    FirebaseApp.initializeApp( options, projectDatabase );

**Comment by hiranya911** [comment] 2017-12-11 22:54
Make sure you're on java8 runtime, and the threadsafe option is enabled in your appengine-web.xml.

To enable debug logging, you need to package a logging.properties file with your app:

```
#logging.properties
.level = INFO
com.google.firebase.level=FINEST
```

Then in your appengine-web.xml:
```
 <system-properties>
        <property name="java.util.logging.config.file" value="WEB-INF/logging.properties"/>
        <property name="java.util.logging.SimpleFormatter.format" value="%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$-6s %2$s %5$s%6$s%n"/>
 </system-properties>
```

**Comment by samodadela** [comment] 2017-12-12 11:22
@hiranya911 we changed the code call initializeApp only once... however when I plug-in the custom ThreadManager all requests start failing. In the logs I see this:

    com.google.firebase.database.logging.LogWrapper debug: Aborting transactions for path: /v1/dev/chat/5708697783238656/-L09NxBPgqOivQ71q7hM. Affected: /v1/dev/chat/5708697783238656/-L09NxBPgqOivQ71q7hM
    com.google.firebase.database.logging.LogWrapper debug: pc_1 - Trying to fetch auth token
    com.google.firebase.database.logging.LogWrapper debug: pc_1 - Error fetching token: com.google.apphosting.api.ApiProxy$CallNotFoundException: Can't make API call urlfetch.Fetch in a thread that is neither the original request thread nor a thread created by ThreadManager 
    com.google.firebase.database.logging.LogWrapper debug: pc_1 - Scheduling connection attempt
    com.google.firebase.database.logging.LogWrapper debug: Scheduling retry in 12734ms 

Because of a problem with java8, we had to add the following in appengine-web.xml:

    <runtime>java8</runtime>
    <url-stream-handler>urlfetch</url-stream-handler>

Most of the log entries don't display the error above. They just timeout waiting on the future.

**Comment by nilsonpontello** [comment] 2017-12-12 12:46
I don't think you have reached the thread limits because GAE won't let you spawn new threads after limit was reached. It throws an exception for such cases with clear explanation of what happened. 

It is more likely you are having a CPU problems then some requests are timing out due to heavy load. This would have happened with any RPC regardless if it is firebase or not.

Instead of having max max 5 **B4** instances, try to setup max 10 **B2** instances and monitor the CPU and number of instances. This will cost maximum what you are paying today but will be cheaper while in off peak.

On the above setup, if the problem is really CPU, the issue shouldn't be reproducible unless GAE has spaw 10 instances.

**Comment by samodadela** [comment] 2017-12-12 14:19
@nilsonpontello could be, though my problem is now with the ThreadManager and fetchUrl... nevertheless it's better if I initialize just one app for all it's databases. I'll test it by decreasing max instances and see what happens.

**Comment by hiranya911** [comment] 2017-12-12 18:20
@samodadela The `<runtime>java</runtime>` option is required. But `url-stream-handler` is a workaround to a problem in GAE if I remember correct. I would expect it to be fixed in prod by now. In fact I have a couple of test java8 apps in GAE prod right now, which are working fine. Did you see this in the dev app server by any chance? If so I would recommend you to try `<url-stream-handler>native</url-stream-handler>`, which should work in both dev app server in prod.

@nilsonpontello When the background threads spawn other background threads, like in the case of Admin RTDB client, we have seen that sometimes things fail silently due to the GAE thread limit. So this is very much a plausible scenario. In fact since @samodadela was running multiple `FirebaseApp` and `FirebaseDatabase` instances, there's a high chance this was happening under the hood.

**Comment by samodadela** [comment] 2017-12-12 22:26
@hiranya911 I changed url-stream-handler to native, passed an instance of ThreadManager to initializeApp() (which is now called only once for all databases in the project) and flooded the server with requests. I did not get any timeouts waiting for Firebase like before - very nice. 

The only errors I got are the following:
- Request was aborted after waiting too long to attempt to service your request.
- Request was aborted because all instances are busy executing other requests. If you are using manual or basic scaling, try increasing the number of instances for this version.

Those errors are expected and indicate that I should increase the number of instances. So this is what happens when GAE doesn't have enough resources to process the requests.

I tested with 5xB4 class and then lowered it to 2xB2... in both cases there were no pesky timeouts just the two errors above. The requests in the task queue were being processed as they should. 

BTW: I also noticed that one instance can process 10 requests simultaneously. It's probably in correlation with the maximum number of threads GAE allows. 

The only remaining thing is I have to check what's the status for the 'urlfetch' java8 workaround.

It would be nice if the findings in this issue make it into the documentation. I'd point out:
- Only one initializeApp() per Firebase project even if it has multiple databases.
- Explain GAE's threading limitation and workaround using ThreadManager (url-stream-handler = native)
- Use GAE/java8
- BasicScalingThreadManager could be a packaged with Firebase Admin - ready to use

@hiranya911 Thank you very much for your help! I certainly wouldn't have figured it out by myself.

**Comment by hiranya911** [comment] 2017-12-12 22:42
Thank you @samodadela. I'm glad it worked out. It was a useful learning experience for us as well. I'll make sure the feedback you've provided are applied towards improving our documentation and APIs.

**Comment by samodadela** [comment] 2017-12-13 17:08
@hiranya911 some more info... the 'native' setting does not work on devserver so we went with 'urlfetch' without ThreadManager... after some time we started getting the timeouts again. I'll try again with 'native' and ThreadManager.

**Comment by samodadela** [comment] 2017-12-13 17:59
@hiranya911 another thing that could cause problems... 

consider this code...

        SettableApiFuture<ValueHolder> future = SettableApiFuture.create();
        final Query mDatabase = FirebaseConfigurationsHelper.getDatabaseReference( firebaseProjectDatabase ).child( path );

        mDatabase.addListenerForSingleValueEvent( new ValueEventListener() {
            @Override
            public void onDataChange( DataSnapshot snapshot ) {

                ValueHolder value = new ValueHolder();
                value.value = snapshot.getValue();

                future.set( value );
            }

            @Override
            public void onCancelled( DatabaseError error ) {
                future.set( null );
            }
        } );

        ValueHolder value = null;

        try {
            value = future.get( FirebaseConfigurationsHelper.FIREBASE_GET_OBJECT_TIMEOUT_DEFAULT_SECONDS, TimeUnit.SECONDS );
        } catch ...

Notice that the future,get() has set a timeout... Maybe the problem is in that when the future times out, the operation does not cleanup its threads? If so... how can I set a timeout on the Firebase operation? I noticed that custom token minting has a get() with a timeout, but other operations don't. 

The primary function of the future in this code is to wait for the operation to complete - otherwise when the function returns the operation is terminated.

**Comment by hiranya911** [comment] 2017-12-13 18:29
In the above example, no additional threads get spawned, except for the fixed number of threads already alive in the database implementation. So there's nothing to clean up.

All Admin SDK methods return an `ApiFuture` at the moment, which has a `get()` method that takes a timeout.

Are you still having issues? Even after applying the custom `ThreadManager`?

**Comment by samodadela** [comment] 2017-12-13 18:38
The problem happened when running without ThreadManager. I'm now running with ThreadManager to see what happens.

You said: 
> All Admin SDK methods return an ApiFuture at the moment, which has a get() method that takes a timeout.

In the example above... where can I get a future?

**Comment by hiranya911** [comment] 2017-12-13 18:57
@samodadela `addListener` methods don't return anything. Plus, the callbacks fire asynchronously. So you need to implement your own synchronization in this case using a `SettableApiFuture` as you've done above, or using a Semaphore.

If our earlier line of reasoning was correct, I would not expect your scenario to work without the custom `ThreadManager`. That's the fix we did -- it forces the SDK to not use GAE background threads. The url stream handler config is a workaround to a [GAE problem](https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2544).

**Comment by samodadela** [comment] 2017-12-13 22:11
@hiranya911 OK, thanks. 
I'll keep monitoring the deployment with the custom ThreadManager and report back.

**Comment by hiranya911** [comment] 2017-12-13 23:11
On a related note GAE Java7 runtime was just deprecated: https://cloud.google.com/appengine/docs/deprecations/java7

I think going forward the Admin SDK should only support the java8 runtime, which simplifies things quite a bit. For instance, we can now implement `BasicScalingThreadManager` is a built-in API and even make it the default.

**Comment by samodadela** [comment] 2017-12-14 08:54
Yesterday I did not manage to test under load, but I noticed that some operations were timing out. The future get() is set to wait 30 seconds. For example, this log entry timed out after 7ms (I timed it in the code):

```
     2017-12-14 08:38:57.469 CET
com.google.firebase.database.logging.LogWrapper debug: conn_579 - received data message: {r=1099, b={d=, s=ok}} (LogWrapper.java:104)
     2017-12-14 08:38:57.469 CET
com.google.firebase.database.logging.LogWrapper debug: pc_0 - m response: {d=, s=ok} (LogWrapper.java:104)
    2017-12-14 08:39:01.184 CET
com.google.firebase.database.logging.LogWrapper debug: ws_578 - Reset keepAlive. Remaining: 0 (LogWrapper.java:104)
    2017-12-14 08:39:19.471 CET
net.d.t.common.metrics.Metrics log: [firebase/updateChildrenAsync/timeout] (Metrics.java:221)
   2017-12-14 08:39:19.471 CET
net.d.t.server.util.firebase.FirebaseHelper$1 onDataChange: updateChildrenAsync timed out! (FirebaseHelper.java:251)
    java.util.concurrent.TimeoutException: Timed out waiting for Task
	at com.google.firebase.tasks.Tasks.await(Tasks.java:133)
	at com.google.firebase.internal.TaskToApiFuture.get(TaskToApiFuture.java:80)
```

Is this firebase timing out internally or some problem with the future? Are those timeouts normal? Do I need to handle such cases and possibly retry?

The code is like this:
```
                // public static int FIREBASE_ADD_ENTRY_TIMEOUT_DEFAULT_SECONDS = 30;

                ApiFuture<Void> request = mDatabase.updateChildrenAsync( childUpdates );
                try {
                    request.get( FirebaseConfigurationsHelper.FIREBASE_ADD_ENTRY_TIMEOUT_DEFAULT_SECONDS, TimeUnit.SECONDS );
                } catch( InterruptedException e ) {
                    log.error( "updateChildrenAsync interrupted!", e );
                } catch( ExecutionException e ) {
                    log.error( "updateChildrenAsync error!", e );
                } catch( TimeoutException e ) {
                    log.error( "updateChildrenAsync timed out!", e );
                }
```

Also - please explain what the "Remaining:" entry in the Firebase log means.

Note: 
- That there was absolutely no load when this happened. 
- I'm using 5.6.0

**Comment by hiranya911** [comment] 2017-12-14 18:14
@samodadela are you saying that the `Future` which should have waited for 30 seconds, timed out only after 7 milliseconds? That sounds like a bug, and we can look into it. How exactly did you measure this? Can you share a code snippet with your timer instrumentation?

The `Remaining:` is an entry periodically logged by the WebSocket connection's idle checker. That doesn't impact you.

**Comment by hiranya911** [comment] 2017-12-14 19:35
It would also be useful to know what your load conditions are. How many concurrent requests, how many update operations, size of an update etc.

I've been running the following test case on my workstation. It runs 32 concurrent threads, each submitting 1000 writes. This completes under a minute, without any errors.

```
  @Test
  public void testLoad() throws Exception {
    final int workers = 32;

    ExecutorService exec = Executors.newFixedThreadPool(workers);
    final FirebaseDatabase database = FirebaseDatabase.getInstance(
        IntegrationTestUtils.ensureDefaultApp());
    List<Future> futures = new ArrayList<>();

    // Start workers
    for (int i = 0; i < workers; i++) {
      final int id = i;
      Future f = exec.submit(new Runnable() {
        @Override
        public void run() {
          // Each worker submits 1000 updates sequentially.
          for (int iter = 0; iter < 1000; iter++) {
            DatabaseReference reference = database.getReference("load_child_" + id);
            Map<String, Object> children = ImmutableMap.<String, Object>of("child", System.nanoTime());
            try {
              reference.updateChildrenAsync(children).get();
              System.out.println("Completed " + id + " " + iter);
            } catch (Exception e) {
              e.printStackTrace();
            }
          }
        }
      });
      futures.add(f);
    }

    // Wait for all workers to finish.
    for (Future f : futures) {
      f.get();
    }
  }
```

**Comment by samodadela** [comment] 2017-12-14 20:46
@hiranya911 about that 7ms timeout - ignore it... I misread the log... I'm having a hard time following the logs... I don't understand why the logs start with com.google.firebase, though I log my message as soon as I'm in the handler (I call firebase later). Really weird... I'll get back when I'm clear what's happening. Am I seeing the log entries from those 5 Firebase threads? 

BTW: I'm now running with ThreadManager and apart some rare timeouts (maybe I'm sending too much data?)  everything works nice.

**Comment by hiranya911** [comment] 2017-12-14 21:37
You seem to have enabled debug logging for the Admin SDK, so it is producing a lot more log entries than usual. Initializing `FirebaseApp` and `FirebaseDatabase` would spawn the database threads, which will start logging immediately. You can adjust the log level in your `logging.properties`.

**Comment by samodadela** [comment] 2017-12-15 13:29
Yeah, thanks - my bad... the reason why I couldn't understand the log is because I was filtering on Errors, but the log in question was split in multiple entries. I was looking at the entry where the error happened and was thinking it was the start of the log. 

I have a few questions regarding the do's/don't so on Firebase:
- I counting the number of user on a certain database. Coming from AppEngine I implemented the counter as sharded. So I have /myShardedCounter/01, /myShardedCounter/02... To increment the counter I randomly choose a shard (01, 02) and increment its value in a transaction. This should lessen contention on the counter in case of many writers. Is sharding even needed on Firebase or could I just have one key (/myCounter)?
- Does the depth of the path affect the speed of operation? Is there a significant difference in speed when accessing /abcdef or /a/b/c/d/e? Should I flatten all paths? I'm just interested in shallow depths - I won't create paths with 100 parts. I like the database to have a nice structure instead of having everything crammed up in /.

**Comment by hiranya911** [comment] 2017-12-15 18:41
* Sharding sounds like the right thing to do in this case -- assuming you have many concurrent writers. Some developers have also proposed other solutions ([example](https://stackoverflow.com/a/15149311/5190886)) for similar problems using Cloud Functions. I would defer this to @mikelehen and @schmidt-sebastian to see if there's a better answer. 
* Flat data models are generally preferred over deeply nested models (see the [best practices guide](https://firebase.google.com/docs/database/web/structure-data#avoid_nesting_data)). There's a cap of 32 on how deep you can nest data in Firebase. Also whenever you retrieve a node you also end up loading all of its child nodes, which is not desirable for large databases.

You should also revisit Firestore at some point, which addresses these concerns better IMO.

**Comment by samodadela** [comment] 2017-12-18 21:33
@hiranya911 Apropos logging... I enabled firebase logging and my logs seem to be mixed up... I'm looking at a log for one operation, but the entries seem to be from another. Can you _confirm_ that I'm seeing a mix of logs from the thread that is processing the request as well as logs from other (firebase) threads? I'm not seeing a thread id  in the log so I don't know which log entry is from the request thread and which are from other threads. Are these the thread_id's: conn_1559, pc_2, ws_1559?

Also: 
- If I register a listener - do I have to remove it before returning/exiting the REST handler? It seems like listeners live on after the handler returns.
- All threads in one app use the same app (initializeApp)... do they share also other stuff? I mean are all operations thread-safe or do I need to lock 'something'?

Status update:
- overall behavior using one initializeApp for all databases and custom ThreadManager is good... the instance works and there are no more 'mass' timeouts (before this change the whole instances went bananas and I had to kill them manually)
- still seeing some spurious timeouts... trying to figure out what's going on, but logs are not very useful

**Comment by hiranya911** [comment] 2017-12-18 23:28
You can set a log pattern in the logging.properties to include a thread ID. But yes, by default logs will be intermingled. There's no way around it in Java.

* If you register a listener using `addValueEventListener()` or `addChildEventListener()`, they will remain active until explicitly removed. You can use `addListenerForSingleValueEvent()` if you want the listener to fire only once.
* No additional locking should be necessary. Within `FirebaseDatabase` everything is thread safe.

**Comment by samodadela** [comment] 2017-12-21 13:43
@hiranya911 We finally got rid of all the timeouts. The problem was in some code that was deleting old chat entries. Because logging is messed up the error was showing also in other requests and made troubleshooting difficult it seemed like there's a general problem with all Firebase calls.  

The problem with the deletion code was that we were registering a listener within a listener. The inner listener was never called and was always timing out. If you know why, please explain. We changed the code to work without nesting listeners and now it works correctly. 

One more thing regarding threads. We run all the Firebase stuff in manual scaled B* instances (task queues) except the custom auth token minting. This runs on autoscaled F* instances. This is needed so that the user gets the token ASAP without having to call the BE twice. Are there any special considerations regarding threads? Should we initializeApp() use ThreadManager in autoscaled F* instances, too?

**Comment by hiranya911** [comment] 2017-12-21 21:48
1. All Firebase database events fire on a single thread (aka EventTarget). Therefore if you add a listener within a listener, and then wait/block until that inner listener fires, it will naturally cause a deadlock -- which will inevitably result in a timeout (since you are blocking the thread that is supposed to fire the inner event listener). In general you should never block or run expensive computations in database event listeners. You should spawn new threads for such tasks as needed.

2.  Not sure why you're getting a rejected execution exception. Haven't seen that in any of my testing. Do you have a repro?

**Comment by samodadela** [comment] 2018-01-08 20:59
@hiranya911 
1. Thanks for the explanation.
2. I can't reproduce it at will - in happens once for ~10000 requests, always when creating the token (which runs on an automatic scaling frontend instance).

**Comment by hiranya911** [comment] 2018-01-08 21:47
Try specifying a custom thread pool and a thread factory (via `ThreadManager` interface) for that instance, and see if that helps. Without a custom `ThreadManager` and background thread support, the SDK will try to spawn a new request-scoped thread for each incoming request (see [implementation](https://github.com/firebase/firebase-admin-java/blob/master/src/main/java/com/google/firebase/internal/GaeExecutorService.java#L186)). May be you're hitting some GAE quota in the process.

Try something like:
```
static class AutoScalingThreadManager extends ThreadManager {

    @Override
    protected ExecutorService getExecutor(@NonNull FirebaseApp firebaseApp) {
      return new ThreadPoolExecutor(0,
          Integer.MAX_VALUE,
          0L,
          TimeUnit.SECONDS,
          new SynchronousQueue<Runnable>(),
          getThreadFactory());
    }

    @Override
    protected void releaseExecutor(@NonNull FirebaseApp firebaseApp,
        @NonNull ExecutorService executorService) {
      executorService.shutdownNow();
    }

    @Override
    protected ThreadFactory getThreadFactory() {
      return Executors.defaultThreadFactory();
    }
}
```

You can also try with a direct (same-thread) executor, and see running the SDK logic on request threads helps with the situation. I haven't tested this, but theoretically it should work.

```
static class DirectThreadManager extends ThreadManager {

    @Override
    protected ExecutorService getExecutor(@NonNull FirebaseApp firebaseApp) {
      return MoreExecutors.newDirectExecutorService();
    }

    @Override
    protected void releaseExecutor(@NonNull FirebaseApp firebaseApp,
        @NonNull ExecutorService executorService) {
      executorService.shutdownNow();
    }

    @Override
    protected ThreadFactory getThreadFactory() {
      return Executors.defaultThreadFactory();
    }
}
```

**Comment by hiranya911** [comment] 2018-01-26 22:02
I believe this is answered/resolved to a satisfactory level. We are also working on dropping GAE java7 runtime support and supporting only java8 runtime, which will make this experience even better in the future. Feel free to reopen if there's anything related to the original timeouts issue.

**Closed by hiranya911** 2018-01-26 22:02 UTC
