### ISSUE TITLE
Is it possible to avoid memory leaks using Firestore on Glassfish/Payara ?

### ISSUE THREAD

**Issue by skonx** [firebase/firebase-admin-java#237] opened 2019-01-04 19:54 UTC
### Describe your environment

  * Operating System version: Ubuntu 16.04 or Docker
  * Firebase SDK version: 6.6.0
  * JVM : Java(TM) SE Runtime Environment (build 1.8.0_191-b12) / Oracle
  * Payara Server: 5.184
  * Firebase Product: Firestore

### Describe the problem

I store few information in Firestore but I can get/update/delete data.
Here is my problem, after undeploying a web application (war) I get these weird errors : 

> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@495224dd]) and a value of type [io.grpc.Context] (value [io.grpc.Context@f94c7c7]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@41a52511]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@41c177f2]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@495224dd]) and a value of type [io.grpc.Context] (value [io.grpc.Context@f94c7c7]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@495224dd]) and a value of type [io.grpc.Context] (value [io.grpc.Context@f94c7c7]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> Severe:   The web application [] created a ThreadLocal with key of type [com.google.api.client.util.escape.Platform$1] (value [com.google.api.client.util.escape.Platform$1@196dc7db]) and a value of type [char[]] (value [[C@306e81ce]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@41a52511]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@588ba77f]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@495224dd]) and a value of type [io.grpc.Context] (value [io.grpc.Context@f94c7c7]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> Severe:   The web application [] created a ThreadLocal with key of type [io.grpc.protobuf.lite.ProtoLiteUtils$1] (value [io.grpc.protobuf.lite.ProtoLiteUtils$1@12bf357b]) and a value of type [java.lang.ref.WeakReference] (value [java.lang.ref.WeakReference@651b7be8]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@41a52511]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@213ff674]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
> 

I'm just using this code : 

```
import com.google.auth.oauth2.GoogleCredentials;
import com.google.cloud.firestore.Firestore;

import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;

// Use a service account
InputStream serviceAccount = new FileInputStream("path/to/serviceAccount.json");
GoogleCredentials credentials = GoogleCredentials.fromStream(serviceAccount);
FirebaseOptions options = new FirebaseOptions.Builder()
    .setCredentials(credentials)
    .build();
FirebaseApp.initializeApp(options);

Firestore db = FirestoreClient.getFirestore();

```

**Comment by hiranya911** [comment] 2019-01-04 21:57
Try calling `close()` on the `Firestore` instance. In the future this will happen automatically when `FirebaseApp.delete()` is called. See #227

**Comment by skonx** [comment] 2019-01-04 22:57
Hi @hiranya911. 
I've already performed a `close()` on the `Firestore` instance. Unfortunately, the errors remain.
Thinking about a potential issue with `io.grpc`, I've implemented [InternalThreadLocalMap.destroy()](https://github.com/netty/netty/issues/6891#issuecomment-374134097). The errors remain.

I've read that `close()` was blocking : [Firestore javadoc](https://googleapis.github.io/google-cloud-java/google-cloud-clients/apidocs/com/google/cloud/firestore/Firestore.html#close--)... but the Threads are not well terminated and seem to be interrupted stopping/undeploying the webapp 😩

**Comment by hiranya911** [comment] 2019-01-04 23:15
Hi @skonx. It seems the problem is deep in the bowels of the Firestore client implementation. Can you report this at https://github.com/googleapis/google-cloud-java. They are the ones who can do something about this. We'll keep this issue open as well for our own tracking.

**Comment by hiranya911** [comment] 2019-01-04 23:18
In RTDB we encountered a similar issue with Netty and fixed it by doing `FastThreadLocal.removeAll()`. It's hacky but that's another thing you can try.

**Comment by skonx** [comment] 2019-01-07 11:30
> In RTDB we encountered a similar issue with Netty and fixed it by doing `FastThreadLocal.removeAll()`. It's hacky but that's another thing you can try.

Thanks @hiranya911. I will test this asap 👍 and keep you post of course. 
BTW, could you please provide best practices regarding firebase/firestore closing? I've not found something in the documentation about closing the db or the firebase app itself.

**Comment by skonx** [comment] 2019-01-07 17:40
Unfortunately, `FastThreadLocal.removeAll()` does not work 😕

**Comment by skonx** [comment] 2019-01-07 18:08
Hi @hiranya911, I've opened an issue as recommended.

**Comment by skonx** [comment] 2019-01-12 13:10
Hi @hiranya911, no response from Google Cloud Java. Could you please push up the opened issue?
It is a real production issue...

**Comment by hiranya911** [comment] 2019-01-14 23:34
@wilhuff can you direct this to somebody at the Firestore SDK side?

@skonx you can also request for free support if this is critical for you: https://firebase.google.com/support/troubleshooter/

**Comment by skonx** [comment] 2019-01-15 19:20
Thanks @hiranya911, google-cloud-java guys replied with a forward from the thread I follow... no real improvement yet 😢

**Comment by skonx** [comment] 2019-01-15 19:22
I understand this a beta product but the impact on performances and security are reals. We are talking about memory leaks. If I did something wrong following the official documentation I'd like to know it.

**Comment by hiranya911** [comment] 2019-01-15 20:56
Thanks for being patient @skonx. I understand the frustration. However, it will take some time to figure this one out--especially since the problem seems to be a bug in Netty, which is not our code. I will keep pinging the Firestore team for an update.

Btw, is there an actual memory leak here? As far as I can tell, the server runtime detects some dangling threads and schedules them for renewal to avoid a potential memory leak. Isn't that correct? If so, the problem may not be as critical as we think.

Also, do we know if this is strictly related to Glassfish/Payara? Any chance we can try this elsewhere, like Tomcat?

Looking at your repro here: https://github.com/trendev/firestore-issue -- can you try tying the FirebaseApp/Firestore initialization and destruction to the lifecycle of the servlet context listener, instead of the servlet? That's how it is supposed to be used.

**Comment by skonx** [comment] 2019-01-15 21:17
Apologizes, I didn’t want to rush you and I hope you didn’t feel bad reading my last post, that was not my intention :)

So, yes it seems to be an issue with netty but I cannot figure it out because the netty’s support requires a test case their api directly, assuming I use firebase admin sdk... I think it will be blocked soon. 

Usually, Java ee servers are very very smart... but when they are overloaded they are a little bit less smart and these optimization may be bypassed... the error is severe so it should be consider as is it because it means it has detected idling/zombie threads during the undeployment. This last state (not expected of course) is the state observed by the server so the memory leaks appear during the runtime!

You’re right it is well controlled but we have no garantie it is the same with a running application. 

I will update the code opening/closing firestore in the servlet context listener. 

BTW, my firestore service will be initialized during the application startup in a singleton.

I’ve implemented firestore init in the servlet for the demonstration. 

I will also test with tomcat or openliberty.

I will post an update tomorrow (it is 10 pm in France and I feel tired 😴).

Thank you for your support and your advise.

**Comment by skonx** [comment] 2019-01-15 21:19
Last note : I’ve tested with Spring and there is the same issue.

**Comment by hiranya911** [comment] 2019-01-15 21:31
Thanks you @skonx. Some very good points there. I will also create an internal bug for the Firestore team to make sure this doesn't fall through the cracks.

**Comment by skonx** [comment] 2019-01-16 13:06
Hi Hiranya.

I've just tested with **Apache Tomcat 9.0.14** and the error is the same : 

> 16-Jan-2019 14:01:31.189 SEVERE [http-nio-8080-exec-3] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [firestore_issue] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@77238e34]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@6fa665d1]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

**Comment by skonx** [comment] 2019-01-16 13:08
So, it is **not server specific**. 

I can also try with OpenLiberty but assuming the test is relevant using Tomcat, Payara and Glassfish, I feel we should focus on the code itself or the dependencies/librairies.

**Comment by skonx** [comment] 2019-01-16 15:10
**Moving Firebase/Firestore initialization/destruction in the `ServletContextListener` is worst.**

## Log/StackTrace from Tomcat : 

> 16-Jan-2019 16:03:24.237 INFO [http-nio-8080-exec-8] org.apache.catalina.util.LifecycleBase.start The start() method was called on component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/firestore_issue]] after start() had already been called. The second call will be ignored.
16-Jan-2019 16:03:33.546 INFO [http-nio-8080-exec-1] fr.trendev.firestore.MyServletContextListener.contextDestroyed ====>>>> [null] is stopping on 1/16/19 4:03 PM
16-Jan-2019 16:03:33.559 INFO [http-nio-8080-exec-1] fr.trendev.firestore.MyServletContextListener.contextDestroyed FirebaseApp and serviceAccount inputstream closed
16-Jan-2019 16:03:33.566 WARNING [http-nio-8080-exec-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [firestore_issue] appears to have started a thread named [grpc-shared-destroyer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
 java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
16-Jan-2019 16:03:33.568 SEVERE [http-nio-8080-exec-1] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [firestore_issue] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@331dc489]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@3e2aaf52]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
16-Jan-2019 16:03:34.081 INFO [http-nio-8080-exec-1] org.apache.catalina.startup.HostConfig.undeploy Undeploying context [/firestore_issue]
16-Jan-2019 16:03:34.559 INFO [grpc-shared-destroyer-0] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1363)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1351)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1211)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1173)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.doStartThread(SingleThreadEventExecutor.java:873)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.shutdownGracefully(SingleThreadEventExecutor.java:587)
	at io.grpc.netty.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.shutdownGracefully(MultithreadEventExecutorGroup.java:163)
	at io.grpc.netty.shaded.io.grpc.netty.Utils$DefaultEventLoopGroupResource.close(Utils.java:203)
	at io.grpc.netty.shaded.io.grpc.netty.Utils$DefaultEventLoopGroupResource.close(Utils.java:182)
	at io.grpc.internal.SharedResourceHolder$2.run(SharedResourceHolder.java:145)
	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16-Jan-2019 16:03:34.561 INFO [grpc-shared-destroyer-0] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise$1]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1363)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1351)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1211)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1173)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.shutdownGracefully(SingleThreadEventExecutor.java:590)
	at io.grpc.netty.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.shutdownGracefully(MultithreadEventExecutorGroup.java:163)
	at io.grpc.netty.shaded.io.grpc.netty.Utils$DefaultEventLoopGroupResource.close(Utils.java:203)
	at io.grpc.netty.shaded.io.grpc.netty.Utils$DefaultEventLoopGroupResource.close(Utils.java:182)
	at io.grpc.internal.SharedResourceHolder$2.run(SharedResourceHolder.java:145)
	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16-Jan-2019 16:03:34.562 INFO [grpc-shared-destroyer-0] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [io.grpc.internal.MoreThrowables]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [io.grpc.internal.MoreThrowables]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1363)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1351)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1211)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1173)
	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

## Log/StackTrace from Payara : 
> Info:   ====>>>> [] is stopping on 1/16/19 4:09 PM
Info:   FirebaseApp and serviceAccount inputstream closed
Severe:   The web application [] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@2f873c94]) and a value of type [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap] (value [io.grpc.netty.shaded.io.netty.util.internal.InternalThreadLocalMap@656da906]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
Severe:   Exception while executing runnable io.grpc.internal.SharedResourceHolder$2@29fc2956
java.lang.IllegalStateException: This web container has not yet been started
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1548)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1505)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432)
	at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.shutdownGracefully(SingleThreadEventExecutor.java:590)
	at io.grpc.netty.shaded.io.netty.util.concurrent.MultithreadEventExecutorGroup.shutdownGracefully(MultithreadEventExecutorGroup.java:163)
	at io.grpc.netty.shaded.io.grpc.netty.Utils$DefaultEventLoopGroupResource.close(Utils.java:203)
	at io.grpc.netty.shaded.io.grpc.netty.Utils$DefaultEventLoopGroupResource.close(Utils.java:182)
	at io.grpc.internal.SharedResourceHolder$2.run(SharedResourceHolder.java:145)
	at io.grpc.internal.LogExceptionRunnable.run(LogExceptionRunnable.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by skonx** [comment] 2019-01-16 15:12
I don't confortable activating/destroying firebase or firestore in the ServletContextListener. 
It should be performed in the Servlet lifecycle... The exceptions are probably thrown because I close firestore before the FirebaseApp, will test that.

**Comment by skonx** [comment] 2019-01-16 15:15
I've removed `fa.delete()` from `contextDestroyed(ServletContextEvent sce)` but the exception remains.

**Comment by skonx** [comment] 2019-01-16 15:16
I'm pushing this code update in a second branch called "**listener**".

**Comment by matejsp** [comment] 2019-01-16 16:01
This is not really a memory leak. Well not when running normally in production.

This is a classloader leak, when application is stopping/redeploying, because running threads are still referencing some classes in threadlocal.

Of course it would be nice to get this fixed, but this is not critical issue as the title suggests. I would fix the issue title to be more appropriate.

**Comment by skonx** [comment] 2019-01-16 16:45
Hi @matejsp.
> This is not really a memory leak. Well not when running normally in production.

I guess you're right but as you mention they are "running threads" and they should not run after the undeployment and by the way if you perform additionnal firestore queries you will get many times this severe log as much as you perform queries. This is where I suspect a real memory leak in fact. The `io.grpc` threads are not closed and the `firestore.close()` does not block waiting the threads are cleaned.

**Comment by wilhuff** [comment] 2019-01-16 18:47
Apologies for the delay in response. I've been doing a bunch of digging on what's going on here.

There are a few interrelated issues here:

  * Firestore's underlying gRPC channels and threads aren't fully shutdown because `Firestore.close()` isn't waiting for shutdown: this is a gax-grpc bug, fixed in googleapis/gax-java#628, first released in gax-grpc 1.36, which was after your initial reports.
  * Netty's thread locals aren't being cleaned up
  * gRPC's Context thread locals aren't being cleaned up

The first fix should address the issue where threads are running past the end of your deployment.

Unfortunately, the other two issues are hard to address. Internal discussion indicates that getting Netty to clean up is possible by shutting down the Netty EventLoopGroup but at this point the plumbing does not exist to be able to control this: it appears that gax-java is just using the default EventLoopGroup. You could conceivably implement an alternative `TransportChannelProvider` that does create its own EventLoopGroup and shuts things down as you like. See [InstantiatingGrpcChannelProvider](https://github.com/googleapis/gax-java/blob/master/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java).

There's currently no mechanism to clean up gRPC thread locals on shutdown. Making this possible requires the addition of an API by the gRPC team.

At this point, considering the scope of what's required to support this kind of redeployment this isn't something the Firestore team can take on. I wish I had a better answer for this, but we have to prioritize and this kind of environment is rare enough that we can't put this ahead of other work we need to do.

My advice is to either increase permgen size and ignore the warnings you're seeing, or shut everything down through public APIs, wait, and then reflectively find ThreadLocals and remove the ThreadLocals that are causing warnings.

**Comment by skonx** [comment] 2019-01-16 20:48
Thank your for this clear explanation. 
I was afraid of that.

**Comment by wilhuff** [comment] 2019-01-16 22:35
OK. Closing for now. If others are trying to use a similar configuration and are running into this we may reconsider.

In the meantime, both gax-java and grpc-java are open source and those teams might accept feature requests to expose this kind of full shutdown control.

I did find some code that shows how to remove ThreadLocals without direct support [on stackoverflow](https://stackoverflow.com/a/16644476). I can't vouch for this and would not use wouldn't enumerate all the thread locals--just the ones that you're specifically getting warnings about in your logs. For example, the gRPC thread local is likely related to [this ThreadLocal declaration](https://github.com/grpc/grpc-java/blob/master/context/src/main/java/io/grpc/ThreadLocalContextStorage.java#L31).

Good luck!

**Closed by wilhuff** 2019-01-16 22:35 UTC
Labels: bug

**Comment by ejona86** [comment] 2019-01-26 06:40
https://github.com/grpc/grpc-java/pull/5290 should fix the Context ThreadLocal.

You can clean up the current thread's Netty ThreadLocal by calling io.netty.util.concurrent.FastThreadLocal.removeAll() or destroy(). While being cleaner than the reflection-based StackOverflow answer, it would be pretty hard to run on all the threads and so isn't really a solution.

**Comment by Amosss** [comment] 2019-05-22 12:11
I just encountered this problem myself with tomcat 9 and I'm using FireStore as well.
Not sure I understood what should be done in order to avoid this error. Please advice, thanks.

**Comment by wilhuff** [comment] 2019-05-23 15:29
Again, this isn't a configuration we can support because not all of our dependencies support it. The Firestore SDK itself does not directly leak via ThreadLocals.

The gRPC PR above, was released as part of grpc-java 1.19, so any version later than will have one fewer ThreadLocal to clean up, but Netty and others will still leak this way so you still need manual clean-up.

If this kind of operation is important to you, then you'll need to add code to reflectively clean these up, as described [above](https://github.com/firebase/firebase-admin-java/issues/237#issuecomment-454970570).

**Comment by Amosss** [comment] 2019-05-23 18:25
What I find weird is that when I work locally (WAR in eclipse), everything is ok with no problem.
When I run remotely (WAR on a linux server), then I get these logs regarding threadlocals.
Is it weird or is it just me who thinks it is?

**Comment by wilhuff** [comment] 2019-05-23 18:42
This likely comes down to differences in configuration between the two environments. I can't comment one way or another on how to resolve it though.
