### ISSUE TITLE
connectTimeout not working if network connection is not available.

### ISSUE THREAD

**Issue by fahadshakeel1989** [firebase/firebase-admin-java#317] opened 2019-10-08 07:36 UTC
### [READ] Step 1: Are you in the right place?
Yes
### [REQUIRED] Step 2: Describe your environment
  * Operating System version: Linux
  * Firebase SDK version: 6.8.1
  * Library version: firebase-admin
  * Firebase Product: Push Notification 

### [REQUIRED] Step 3: Describe the problem
connectTimeout configured in FirebaseOptions object is not working if network connection is not available. Getting SocketTimeoutException once default http connect timeout occurs i.e. 60 seconds.

#### Steps to reproduce:

1. Configure connectTimeout in FirebaseOptions object.
2. Initialize FirebaseApp instance.
3. Get FirebaseMessaging instance.
4. Call send() method.

#### Relevant Code:
```
InetSocketAddress inetSocketAddress = new InetSocketAddress(proxy_ip, proxy_port);

HttpTransport httpTransport = new NetHttpTransport.Builder()
        .setProxy(new Proxy(Proxy.Type.HTTP, inetSocketAddress))
        .build();

HttpTransportFactory httpTransaportFactory = new HttpTransportFactory() {
        @Override
        public HttpTransport create() {
                return httpTransport
        }
};

GoogleCredentials googleCredentials = GoogleCredentials.fromStream(serviceAccount, httpTransaportFactory);

FirebaseOptions firebaseOptions = new FirebaseOptions.Builder()
        .setCredentials(googleCredentials)
        .setHttpTransport(httpTransport)
        .setConnectTimeout(2*1000)
        .setReadTimeout(3*1000)
        .build();

FirebaseApp firebaseApp = FirebaseApp.initializeApp(firebaseOptions);

FirebaseMessaging.getInstance(firebaseApp).send(message);
```

**Comment by hiranya911** [comment] 2019-10-08 17:20
I ran into this recently myself. This is because the connect timeout setting in `FirebaseOptions` does not effect the transport used by `GoogleCredentials` (the very first request made by the SDK is through `GoogleCredentials` to fetch access tokens). And I don't see a straight forward way to set a timeout for `GoogleCredentials` either.

**Comment by hiranya911** [comment] 2019-10-08 18:13
I just filed https://github.com/googleapis/google-auth-library-java/issues/356 regarding this. 

I've also learned that `GoogleCredentials` retries requests 10 times with exponential backoff. So in the event of a complete network outage, all the delay you're seeing is caused by these delayed retries.

**Comment by hiranya911** [comment] 2021-02-05 23:03
Closing in favor of the issue filed at upstream google-auth repo.

**Closed by hiranya911** 2021-02-05 23:03 UTC
Labels: feature-request
